name: publish-image

on:
  push:
    tags:
      - "v*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Extract meta
        id: meta
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          BUN_VERSION=$(echo "$TAG" | sed -nE 's/.*bun-([0-9.]+).*/\1/p')
          PUPPETEER_VERSION=$(echo "$TAG" | sed -nE 's/.*puppetter-([0-9.]+).*/\1/p')
          echo "image_tag=$TAG" >> $GITHUB_OUTPUT
          echo "bun_version=$BUN_VERSION" >> $GITHUB_OUTPUT
          echo "puppeteer_version=$PUPPETEER_VERSION" >> $GITHUB_OUTPUT
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            BUN_VERSION=${{ steps.meta.outputs.bun_version }}
            PUPPETEER_VERSION=${{ steps.meta.outputs.puppeteer_version }}
          push: true
          tags: ghcr.io/cubic-lab/bun-puppeteer:${{ steps.meta.outputs.image_tag }}